### ISSUE TITLE
Empty set in "Inverse species and sign-reversing involutions"

### ISSUE THREAD

**Issue by SuprDewd** [akc/www.akc.is#2]
There are not equally many subsets of even and odd parity of the empty set. This explains why *0^0 = 1* in the first proof, and why *E\*E^{-1} = 1* has this *1* on the right side.

It feels a bit like this issue is swept under the rug, e.g. by assuming that *n* is positive in the first part. I would prefer if this special case was incorporated into the post, and then used to explain this *1* in *E\*E^{-1} = 1*.

**Comment by akc** [comment]
That's a good point and I will try to clear that up.
